<?xml version="1.0" encoding="UTF-8"?>
<!--ROMRAIDER METRIC UNITS LOGGER DEFINITION FILE (VERSION 370) 20211116_191942 [de]
363 20211115_191632 Updated ECU ID: 4B0A377007 extended parameters Changed address/length/bit entry for ECU ID 4B0A377007 for extended parameter E56
364 20211115_192241 Added ECU ID: CD2A904007 to extended parameters
365 20211115_192824 Added ECU ID: 6CF2504007 to extended parameters
366 20211115_193234 Added ECU ID: 5222168107 to extended parameters
367 20211115_195926 Added ECU ID: 4E22048007 to extended parameters
368 20211116_191013 Update MS43 parameters from https://github.com/ba114/Siemens-MS43
369 20211116_191723 Added MSS52 parameters from https://github.com/ba114/MSS52
370 20211116_191942 Add Nissan CAN Support

TERMS, CONDITIONS, AND DISCLAIMERS
- - - - - - - - - - - - - - - - - - - - - - - - -
WARNING: These definition files are created as the result of the extremely complex and time consuming process
of reverse-engineering the factory ECU. Because of this complexity, it is necessary to make certain assumptions
and, therefore, it is impossible to always deal in absolutes in regards to representations made by these
definitions. In addition, due to this complexity and the numerous variations among different ECUs, it is also
impossible to guarantee that the definitions will not contain errors or other bugs. What this all means is that
there is the potential for bugs, errors and misrepresentations which can result in damage to your motor, your
ECU as well the possibility of causing your vehicle to behave unexpectedly on the road, increasing the risk of
death or injury. Modifications to your vehicle's ECU may also be in violation of local, state and federal laws.
By using these definition files, either directly or indirectly, you agree to assume 100% of all risk and
RomRaider's creators and contributors shall not be held responsible for any damages or injuries you receive.
This product is for advanced users only. There are no safeguards in place when tuning with RomRaider. As such,
the potential for serious damage and injury still exists, even if the user does not experience any bugs or errors.
As always, use at your own risk.

These definitions are created for FREE without any sort of guarantee. The developers cannot be held liable for
any damage or injury incurred as a result of these definitions. USE AT YOUR OWN RISK! -->
<!DOCTYPE logger [

<!ELEMENT address ( #PCDATA ) >
<!ATTLIST address length CDATA #IMPLIED >
<!ATTLIST address bit ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 ) #IMPLIED >

<!ELEMENT ecu ( address+ ) >
<!ATTLIST ecu id CDATA #REQUIRED >

<!ELEMENT ref EMPTY >
<!ATTLIST ref ecuparam CDATA #IMPLIED >
<!ATTLIST ref parameter IDREF #IMPLIED >

<!ELEMENT depends ( ref+ ) >

<!ELEMENT replace EMPTY >
<!ATTLIST replace value CDATA #REQUIRED >
<!ATTLIST replace with CDATA #REQUIRED >

<!ELEMENT conversion ( replace* ) >
<!ATTLIST conversion expr CDATA #REQUIRED >
<!ATTLIST conversion format ( 0 | 0.0 | 0.00 | 0.000 | 0.0000 | 0.00000 | 0.000000) #REQUIRED >
<!ATTLIST conversion storagetype ( int8 | int16 | uint8 | uint16 | int32 | uint32 | float ) #IMPLIED >
<!ATTLIST conversion endian CDATA #IMPLIED >
<!ATTLIST conversion units CDATA #REQUIRED >
<!ATTLIST conversion gauge_min CDATA #IMPLIED >
<!ATTLIST conversion gauge_max CDATA #IMPLIED >
<!ATTLIST conversion gauge_step CDATA #IMPLIED >

<!ELEMENT conversions ( conversion+ ) >

<!ELEMENT parameter ( ( address+, conversions?) | (depends, conversions?) ) >
<!ATTLIST parameter target CDATA #REQUIRED >
<!ATTLIST parameter ecubit ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 ) #IMPLIED >
<!ATTLIST parameter ecubyteindex CDATA #IMPLIED >
<!ATTLIST parameter desc CDATA #REQUIRED >
<!ATTLIST parameter name CDATA #REQUIRED >
<!ATTLIST parameter id ID #REQUIRED >

<!ELEMENT parameters ( parameter+ ) >
<!ATTLIST parameters mode CDATA #IMPLIED >

<!ELEMENT switch EMPTY >
<!ATTLIST switch target CDATA #REQUIRED >
<!ATTLIST switch ecubyteindex CDATA #IMPLIED >
<!ATTLIST switch bit ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 ) #REQUIRED >
<!ATTLIST switch byte CDATA #REQUIRED >
<!ATTLIST switch desc CDATA #REQUIRED >
<!ATTLIST switch name CDATA #REQUIRED >
<!ATTLIST switch id ID #REQUIRED >

<!ELEMENT switches ( switch+ ) >

<!ELEMENT dtcode EMPTY >
<!ATTLIST dtcode bit ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 ) #REQUIRED >
<!ATTLIST dtcode memaddr CDATA #REQUIRED >
<!ATTLIST dtcode tmpaddr CDATA #REQUIRED >
<!ATTLIST dtcode desc CDATA #REQUIRED >
<!ATTLIST dtcode name CDATA #REQUIRED >
<!ATTLIST dtcode id ID #REQUIRED >

<!ELEMENT dtcodes ( dtcode+) >

<!ELEMENT ecuparam ( ecu+, conversions? ) >
<!ATTLIST ecuparam target CDATA #REQUIRED >
<!ATTLIST ecuparam groupsize CDATA #IMPLIED >
<!ATTLIST ecuparam subgroup CDATA #IMPLIED >
<!ATTLIST ecuparam group CDATA #IMPLIED >
<!ATTLIST ecuparam desc CDATA #REQUIRED >
<!ATTLIST ecuparam name CDATA #REQUIRED >
<!ATTLIST ecuparam id ID #REQUIRED >

<!ELEMENT ecuparams ( ecuparam+ ) >

<!ELEMENT module EMPTY >
<!ATTLIST module fastpoll CDATA #IMPLIED >
<!ATTLIST module tester CDATA #IMPLIED >
<!ATTLIST module desc CDATA #REQUIRED >
<!ATTLIST module address CDATA #REQUIRED >
<!ATTLIST module id ID #REQUIRED >

<!ELEMENT transport ( module+ ) >
<!ATTLIST transport desc CDATA #REQUIRED >
<!ATTLIST transport name CDATA #REQUIRED >
<!ATTLIST transport id ID #REQUIRED >

<!ELEMENT transports ( transport+ ) >

<!ELEMENT protocol ( transports, parameters?, switches?, dtcodes?, ecuparams? ) >
<!ATTLIST protocol id ID #REQUIRED >
<!ATTLIST protocol baud CDATA #REQUIRED >
<!ATTLIST protocol databits CDATA #REQUIRED >
<!ATTLIST protocol stopbits CDATA #REQUIRED >
<!ATTLIST protocol parity CDATA #REQUIRED >
<!ATTLIST protocol connect_timeout CDATA #REQUIRED >
<!ATTLIST protocol send_timeout CDATA #REQUIRED >

<!ELEMENT protocols ( protocol+ ) >

<!ELEMENT logger ( protocols ) >
<!ATTLIST logger version CDATA #IMPLIED >
]>
<logger version="370">
    <protocols>
        <protocol id="SSM" baud="4800" databits="8" stopbits="1" parity="0" connect_timeout="2000" send_timeout="55">
            <transports>
                <transport id="iso9141" name="K-Line" desc="Low speed serial protocol supported up to ~MY2014.">
                    <module id="ecu" address="0x10" desc="Engine Control Unit" tester="0xF0" fastpoll="true"/>
                    <module id="tcu" address="0x18" desc="Transmission Control Unit" tester="0xF0"  fastpoll="false"/>
                </transport>
                <transport id="iso15765" name="CAN bus" desc="CAN bus logging ~MY2007+.">
                    <module id="ecu" address="0x000007E8" desc="Engine Control Unit" tester="0x000007E0" />
                    <module id="tcu" address="0x000007E9" desc="Transmission Control Unit" tester="0x000007E1" />
                </transport>
            </transports>
            <parameters>
                <parameter id="P1" name="Motorlast (relative)" desc="P1" ecubyteindex="8" ecubit="7" target="1">
                    <address>0x000007</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P2" name="Kühlmitteltemperatur" desc="P2" ecubyteindex="8" ecubit="6" target="1">
                    <address>0x000008</address>
                    <conversions>
                        <conversion units="C" expr="x-40" format="0" gauge_min="-20" gauge_max="120" gauge_step="20" />
                        <conversion units="F" expr="32+9*(x-40)/5" format="0" gauge_min="0" gauge_max="240" gauge_step="30" />
                    </conversions>
                </parameter>
                <parameter id="P3" name="Gemischkorrektur #1" desc="P3" ecubyteindex="8" ecubit="5" target="1">
                    <address>0x000009</address>
                    <conversions>
                        <conversion units="%" expr="(x-128)*100/128" format="0.00" gauge_min="-20" gauge_max="20" gauge_step="5" />
                    </conversions>
                </parameter>
                <parameter id="P4" name="Gemisch Lernwert #1" desc="P4" ecubyteindex="8" ecubit="4" target="1">
                    <address>0x00000A</address>
                    <conversions>
                        <conversion units="%" expr="(x-128)*100/128" format="0.00" gauge_min="-20" gauge_max="20" gauge_step="5" />
                    </conversions>
                </parameter>
                <parameter id="P5" name="Gemischkorrektur #2" desc="P5" ecubyteindex="8" ecubit="3" target="1">
                    <address>0x00000B</address>
                    <conversions>
                        <conversion units="%" expr="(x-128)*100/128" format="0.00" gauge_min="-20" gauge_max="20" gauge_step="5" />
                    </conversions>
                </parameter>
                <parameter id="P6" name="Gemisch Lernwert #2" desc="P6" ecubyteindex="8" ecubit="2" target="1">
                    <address>0x00000C</address>
                    <conversions>
                        <conversion units="%" expr="(x-128)*100/128" format="0.00" gauge_min="-20" gauge_max="20" gauge_step="5" />
                    </conversions>
                </parameter>
                <parameter id="P7" name="Ansaugkrümmer Absolutdruck" desc="P7-Druck-Wert aus dem Ansaugkrümmer-Absolutdruck Sensor berechnet (absolut)" ecubyteindex="8" ecubit="1" target="1">
                    <address>0x00000D</address>
                    <conversions>
                        <conversion units="kPa" expr="x" format="0" gauge_min="-120" gauge_max="280" gauge_step="40" />
                        <conversion units="hPa" expr="x*10" format="0" gauge_min="-1200" gauge_max="2800" gauge_step="400" />
                        <conversion units="bar" expr="x/100" format="0.000" gauge_min="-1.2" gauge_max="2.8" gauge_step="0.4" />
                        <conversion units="psi" expr="x*37/255" format="0.00" gauge_min="-20" gauge_max="40" gauge_step="5" />
                        <conversion units="inHg" expr="x*0.2953" format="0.00" gauge_min="-40" gauge_max="60" gauge_step="10" />
                        <conversion units="mmHg" expr="x*7.5" format="0" gauge_min="-1000" gauge_max="2000" gauge_step="300" />
                    </conversions>
                </parameter>
                <parameter id="P8" name="Motordrehzahl" desc="P8" ecubyteindex="8" ecubit="0" target="3">
                    <address length="2">0x00000E</address>
                    <conversions>
                        <conversion units="rpm" expr="x/4" format="0" />
                    </conversions>
                </parameter>
                <parameter id="P9" name="Fahrzeuggeschwindigkeit" desc="P9" ecubyteindex="9" ecubit="7" target="1">
                    <address>0x000010</address>
                    <conversions>
                        <conversion units="km/h" expr="x" format="0" gauge_min="0" gauge_max="300" gauge_step="30" />
                        <conversion units="mph" expr="x*0.621371192" format="0" gauge_min="0" gauge_max="250" gauge_step="25" />
                    </conversions>
                </parameter>
                <parameter id="P10" name="Zündzeitpunkt" desc="P10" ecubyteindex="9" ecubit="6" target="1">
                    <address>0x000011</address>
                    <conversions>
                        <conversion units="degrees" expr="(x-128)/2" format="0.00" gauge_min="20" gauge_max="60" gauge_step="10" />
                    </conversions>
                </parameter>
                <parameter id="P11" name="Ladelufttemperatur (LLT)" desc="P11-Ladelufttemperatur bei Turbo, Ansaugtemperatur bei Saugmotoren" ecubyteindex="9" ecubit="5" target="1">
                    <address>0x000012</address>
                    <conversions>
                        <conversion units="C" expr="x-40" format="0" gauge_min="-20" gauge_max="60" gauge_step="10" />
                        <conversion units="F" expr="32+9*(x-40)/5" format="0" gauge_min="0" gauge_max="140" gauge_step="20" />
                    </conversions>
                </parameter>
                <parameter id="P12" name="Luftmasse (absolut)" desc="P12" ecubyteindex="9" ecubit="4" target="1">
                    <address length="2">0x000013</address>
                    <conversions>
                        <conversion units="g/s" expr="x/100" format="0.00" gauge_min="0" gauge_max="400" gauge_step="20" />
                    </conversions>
                </parameter>
                <parameter id="P13" name="Drosselklappe Öffnungswinkel" desc="P13-Motor Drosselöffnungswinkel" ecubyteindex="9" ecubit="3" target="1">
                    <address>0x000015</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P14" name="Lambdasonde vor Kat #1" desc="P14" ecubyteindex="9" ecubit="2" target="1">
                    <address length="2">0x000016</address>
                    <conversions>
                        <conversion units="V" expr="x/200" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P15" name="Lambdasonde nach KAT #1" desc="P15" ecubyteindex="9" ecubit="1" target="1">
                    <address length="2">0x000018</address>
                    <conversions>
                        <conversion units="V" expr="x/200" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P16" name="Lambdasonde vor Kat #2" desc="P16" ecubyteindex="9" ecubit="0" target="1">
                    <address length="2">0x00001A</address>
                    <conversions>
                        <conversion units="V" expr="x/200" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P17" name="Batteriespannung" desc="P17" ecubyteindex="10" ecubit="7" target="3">
                    <address>0x00001C</address>
                    <conversions>
                        <conversion units="V" expr="x*8/100" format="0.00" gauge_min="0" gauge_max="20" gauge_step="2" />
                    </conversions>
                </parameter>
                <parameter id="P18" name="Spannung Luftmassen Sensor" desc="P18" ecubyteindex="10" ecubit="6" target="3">
                    <address>0x00001D</address>
                    <conversions>
                        <conversion units="V" expr="x/50" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P19" name="Spannung Drosselklappen Sensor" desc="P19" ecubyteindex="10" ecubit="5" target="3">
                    <address>0x00001E</address>
                    <conversions>
                        <conversion units="V" expr="x/50" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P20" name="Spannung Differenzdruck-Sensor" desc="P20" ecubyteindex="10" ecubit="4" target="1">
                    <address>0x00001F</address>
                    <conversions>
                        <conversion units="V" expr="x/50" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P21" name="Einspritzdauer Injektor #1 (Plusweite)" desc="P21-Dieser Parameter enthält Injektor Latenz." ecubyteindex="10" ecubit="3" target="1">
                    <address>0x000020</address>
                    <conversions>
                        <conversion units="ms" expr="x*256/1000" format="0.00" />
                        <conversion units="µs" expr="x*256" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P22" name="Einspritzdauer Injektor #2 (Plusweite)" desc="P22-Dieser Parameter enthält Injektor Latenz." ecubyteindex="10" ecubit="2" target="1">
                    <address>0x000021</address>
                    <conversions>
                        <conversion units="ms" expr="x*256/1000" format="0.00" />
                        <conversion units="µs" expr="x*256" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P23" name="korrektur Klopfen" desc="P23-Retard amount when knocking has occurred. Partial learned value of the learned ignition timing." ecubyteindex="10" ecubit="1" target="1">
                    <address>0x000022</address>
                    <conversions>
                        <conversion units="degKW" expr="(x-128)/2" format="0.00" gauge_min="-15" gauge_max="20" gauge_step="5" />
                    </conversions>
                </parameter>
                <parameter id="P24" name="Umgebungsdruck" desc="P24" ecubyteindex="10" ecubit="0" target="1">
                    <address>0x000023</address>
                    <conversions>
                        <conversion units="kPa" expr="x" format="0" gauge_min="0" gauge_max="255" gauge_step="20" />
                        <conversion units="hPa" expr="x*10" format="0" gauge_min="0" gauge_max="1500" gauge_step="100" />
                        <conversion units="bar" expr="x/100" format="0.000" gauge_min="0" gauge_max="1.5" gauge_step="0.1" />
                        <conversion units="psi" expr="x*37/255" format="0.00" gauge_min="0" gauge_max="20" gauge_step="2" />
                        <conversion units="inHg" expr="x*0.2953" format="0.00" gauge_min="-40" gauge_max="60" gauge_step="10" />
                        <conversion units="mmHg" expr="x*7.5" format="0" gauge_min="-1000" gauge_max="2000" gauge_step="300" />
                    </conversions>
                </parameter>
                <parameter id="P25" name="Saugrohr Druck (LD relativ)" desc="P25-Ladedruck relative bei Turbomotoren" ecubyteindex="11" ecubit="7" target="1">
                    <address>0x000024</address>
                    <conversions>
                        <conversion units="kPa" expr="x-128" format="0" gauge_min="-130" gauge_max="130" gauge_step="20" />
                        <conversion units="hPa" expr="(x-128)*10" format="0" gauge_min="-2000" gauge_max="2000" gauge_step="400" />
                        <conversion units="bar" expr="(x-128)/100" format="0.000" gauge_min="-2" gauge_max="2" gauge_step="0.4" />
                        <conversion units="psi" expr="(x-128)*37/255" format="0.00" gauge_min="-30" gauge_max="30" gauge_step="5" />
                    </conversions>
                </parameter>
                <parameter id="P26" name="Differenzdruck Sensor" desc="P26" ecubyteindex="11" ecubit="6" target="1">
                    <address>0x000025</address>
                    <conversions>
                        <conversion units="kPa" expr="x-128" format="0" gauge_min="-130" gauge_max="130" gauge_step="20" />
                        <conversion units="hPa" expr="(x-128)*10" format="0" gauge_min="-2000" gauge_max="2000" gauge_step="400" />
                        <conversion units="bar" expr="(x-128)/100" format="0.000" />
                        <conversion units="psi" expr="(x-128)*37/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P27" name="Kraftstofftank Innendruck" desc="P27" ecubyteindex="11" ecubit="5" target="1">
                    <address>0x000026</address>
                    <conversions>
                        <conversion units="kPa" expr="(x-128)/40" format="0.00" gauge_min="-5" gauge_max="5" gauge_step="1" />
                        <conversion units="hPa" expr="(x-128)/4" format="0" />
                        <conversion units="bar" expr="(x-128)/4000" format="0.000" />
                        <conversion units="psi" expr="(x-128)*35/10000" format="0.000" />
                    </conversions>
                </parameter>
                <parameter id="P28" name="CO Korrektur" desc="P28" ecubyteindex="11" ecubit="4" target="1">
                    <address>0x000027</address>
                    <conversions>
                        <conversion units="V" expr="x/50" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P29" name="Lernwert Zündzeitpunkt" desc="P29-Erweiterung oder Zurücknahme des Zündzeitpunktes wenn Klopfen registriert" ecubyteindex="11" ecubit="3" target="1">
                    <address>0x000028</address>
                    <conversions>
                        <conversion units="degrees" expr="(x-128)/2" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P30" name="Fahrpedal (Stellung)" desc="P30-Pedalweg 0..100%." ecubyteindex="11" ecubit="2" target="3">
                    <address>0x000029</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P31" name="Kraftstofftemperatur" desc="P31" ecubyteindex="11" ecubit="1" target="1">
                    <address>0x00002A</address>
                    <conversions>
                        <conversion units="C" expr="x-40" format="0" gauge_min="-20" gauge_max="60" gauge_step="10" />
                        <conversion units="F" expr="32+9*(x-40)/5" format="0" gauge_min="0" gauge_max="140" gauge_step="20" />
                    </conversions>
                </parameter>
                <parameter id="P32" name="Vordere Lambdasonde Heizstrom #1" desc="P32" ecubyteindex="11" ecubit="0" target="1">
                    <address>0x00002B</address>
                    <conversions>
                        <conversion units="A" expr="x*1004/25600" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P33" name="Hintere Lambdasonde Heizstrom" desc="P33" ecubyteindex="12" ecubit="7" target="1">
                    <address>0x00002C</address>
                    <conversions>
                        <conversion units="A" expr="x*1004/25600" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P34" name="Vordere Lambdasonde Heizstrom #2" desc="P34" ecubyteindex="12" ecubit="6" target="1">
                    <address>0x00002D</address>
                    <conversions>
                        <conversion units="A" expr="x*1004/25600" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P35" name="Kraftstoffmenge (Tankgeber Rohwert)" desc="P35-Signalspannung des Tankgebers" ecubyteindex="12" ecubit="5" target="1">
                    <address>0x00002E</address>
                    <conversions>
                        <conversion units="V" expr="x/50" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P36" name="VTG Ansteuerung prim. (TV)" desc="P36-Ansteuerung des Ladedruckregelventils" ecubyteindex="12" ecubit="3" target="1">
                    <address>0x000030</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P37" name="VTG Ansteuerung sek.(VT)" desc="P37-Ansteuerung bei Bi- oder Twinturbo Motoren" ecubyteindex="12" ecubit="2" target="1">
                    <address>0x000031</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P38" name="CPC Ventil Ansteuereung (TV)" desc="P38" ecubyteindex="12" ecubit="1" target="1">
                    <address>0x000032</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P39" name="Tumble Valve Position Sensor Right" desc="P39" ecubyteindex="12" ecubit="0" target="1">
                    <address>0x000033</address>
                    <conversions>
                        <conversion units="V" expr="x/50" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P40" name="Tumble Valve Position Sensor Left" desc="P40" ecubyteindex="13" ecubit="7" target="1">
                    <address>0x000034</address>
                    <conversions>
                        <conversion units="V" expr="x/50" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P41" name="Leerlaufregelerventil Ansteuerung (TV)" desc="P41" ecubyteindex="13" ecubit="6" target="1">
                    <address>0x000035</address>
                    <conversions>
                        <conversion units="%" expr="x/2" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P42" name="Gemischkorrektur mager" desc="P42" ecubyteindex="13" ecubit="5" target="1">
                    <address>0x000036</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P43" name="Gemischheizung Ansteuerung (TV)" desc="P43" ecubyteindex="13" ecubit="4" target="1">
                    <address>0x000037</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P44" name="Leerlaufsteller Stufen" desc="P44" ecubyteindex="13" ecubit="3" target="1">
                    <address>0x000038</address>
                    <conversions>
                        <conversion units="Stufe" expr="x" format="0" />
                    </conversions>
                </parameter>
                <parameter id="P45" name="AGR Steller Stufen" desc="P45" ecubyteindex="13" ecubit="2" target="1">
                    <address>0x000039</address>
                    <conversions>
                        <conversion units="Stufe" expr="x" format="0" />
                    </conversions>
                </parameter>
                <parameter id="P46" name="Generatorlast" desc="P46" ecubyteindex="13" ecubit="1" target="1">
                    <address>0x00003A</address>
                    <conversions>
                        <conversion units="%" expr="x" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P47" name="Krafstoffpumpenlast" desc="P47" ecubyteindex="13" ecubit="0" target="1">
                    <address>0x00003B</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P48" name="Ansaug VVT Verstellwinkel rechts" desc="P48" ecubyteindex="14" ecubit="7" target="1">
                    <address>0x00003C</address>
                    <conversions>
                        <conversion units="degrees" expr="x-50" format="0" gauge_min="0" gauge_max="50" gauge_step="5" />
                    </conversions>
                </parameter>
                <parameter id="P49" name="Ansaug VVT Verstellwinkel links" desc="P49" ecubyteindex="14" ecubit="6" target="1">
                    <address>0x00003D</address>
                    <conversions>
                        <conversion units="degrees" expr="x-50" format="0" gauge_min="0" gauge_max="50" gauge_step="5" />
                    </conversions>
                </parameter>
                <parameter id="P50" name="Ansaug OCV Last rechts" desc="P50" ecubyteindex="14" ecubit="5" target="1">
                    <address>0x00003E</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P51" name="Ansaug OCV Last links" desc="P51" ecubyteindex="14" ecubit="4" target="1">
                    <address>0x00003F</address>
                    <conversions>
                        <conversion units="%" expr="x*100/255" format="0.00" />
                    </conversions>
                </parameter>
                <parameter id="P52" name="Ansaug OCV Strom rechts" desc="P52" ecubyteindex="14" ecubit="3" target="1">
                    <address>0x000040</address>
                    <conversions>
                        <conversion units="mA" expr="x*32" format="0" />
                    </conversions>
                </parameter>
                <parameter id="P53" name="Ansaug OCV Strom links" desc="P53" ecubyteindex="14" ecubit="2" target="1">
                    <address>0x000041</address>
                    <conversions>
                        <conversion units="mA" expr="x*32" format="0" />
                    </conversions>
                </parameter>
                <parameter id="P54" name="Lambdasonde #1 Strom" desc="P54" ecubyteindex="14" ecubit="1" target="1">
                    <address>0x000042</address>
                    <conversions>
                        <conversion units="mA" expr="(x-128)/8" format="0.00" />
                    </conversions>
                </parameter>